name: flutter_attendance_app
description: Smart Attendance System Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  csv: ^5.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
